export const YOUTUBE_VISIBILITY_CONSTANT: {
  PUBLIC: "PUBLIC"
  PRIVATE: "PRIVATE"
  UNLISTED: "UNLISTED"
} = {
  PUBLIC: "PUBLIC",
  PRIVATE: "PRIVATE",
  UNLISTED: "UNLISTED",
}

export const YOUTUBE_POST_AS_CONSTANT: {
  SHORTS: "SHORTS"
  VIDEO: "VIDEO"
} = {
  SHORTS: "SHORTS",
  VIDEO: "VIDEO",
}
