export type SCHEDULE_TYPE = "CUSTOM" | "NEXT" | "INSTANT" | "SLOT"

export type POST_TYPE = "IMAGE" | "VIDEO" | "TEXT" | "LINK"

export type POST_STATUS = "QUEUED" | "SENT" | "DRAFT" | "FAILED"

export type POST_VISIBILITY = "PUBLIC" | "PRIVATE" | "UNLISTED"

// export type POST_ON =
//   | "FACEBOOK"
//   | "INSTAGRAM"
//   | "LINKEDIN"
//   | "PINTEREST"
//   | "TIKTOK"
//   | "YOUTUBE"
//   | "GMB"
//   | "TWITTER"
//   | "TUMBLR"
//   | "REDDIT"
//   | "SNAPCHAT"

export type POST_ON =
  | "FACEBOOK"
  | "INSTAGRAM"
  | "LINKEDIN"
  | "PINTEREST"
  | "TIKTOK"
  | "YOUTUBE"
  | "GMB"
  | "TWITTER"
  | "TUMBLR"

export const SCHEDULE_TYPE_CONSTANT: {
  CUSTOM: "CUSTOM"
  INSTANT: "INSTANT"
  NEXT: "NEXT"
  SLOT: "SLOT"
} = {
  CUSTOM: "CUSTOM",
  NEXT: "NEXT",
  INSTANT: "INSTANT",
  SLOT: "SLOT",
}

export const POST_TYPE_CONSTANT: {
  IMAGE: "IMAGE"
  VIDEO: "VIDEO"
  TEXT: "TEXT"
  LINK: "LINK"
} = {
  IMAGE: "IMAGE",
  VIDEO: "VIDEO",
  TEXT: "TEXT",
  LINK: "LINK",
}

export const POST_STATUS_CONSTANT: {
  QUEUED: "QUEUED"
  SENT: "SENT"
  DRAFT: "DRAFT"
  FAILED: "FAILED"
} = {
  QUEUED: "QUEUED",
  SENT: "SENT",
  DRAFT: "DRAFT",
  FAILED: "FAILED",
}

export const POST_VISIBILITY_CONSTANT: {
  PUBLIC: "PUBLIC"
  PRIVATE: "PRIVATE"
  UNLISTED: "UNLISTED"
} = {
  PUBLIC: "PUBLIC",
  PRIVATE: "PRIVATE",
  UNLISTED: "UNLISTED",
}

export const POST_ON_CONSTANT: {
  FACEBOOK: "FACEBOOK"
  INSTAGRAM: "INSTAGRAM"
  LINKEDIN: "LINKEDIN"
  PINTEREST: "PINTEREST"
  TIKTOK: "TIKTOK"
  YOUTUBE: "YOUTUBE"
  GMB: "GMB"
  TWITTER: "TWITTER"
  TUMBLR: "TUMBLR"
} = {
  FACEBOOK: "FACEBOOK",
  INSTAGRAM: "INSTAGRAM",
  LINKEDIN: "LINKEDIN",
  PINTEREST: "PINTEREST",
  TIKTOK: "TIKTOK",
  YOUTUBE: "YOUTUBE",
  GMB: "GMB",
  TWITTER: "TWITTER",
  TUMBLR: "TUMBLR",
}